### ISSUE TITLE
Mapping the 3D structure of all chromosomes of the whole genome

### ISSUE THREAD

**Issue by shenlinyong** [wangjr03/FLAMINGO#3]
The software you have developed is very perfect and useful. But I am a little confused, the `chr_name` parameter is mandatory if I want to build all chromosomes in the genome to a 3D result model, not just one chromosome. What should I do again?

**Comment by haowang0508** [comment]
> 

Hi,
Thanks for using our software.
Yes, the chr_name parameter is mandatory since FLAMINGO reconstructs the chromosome structure only based on the intra-chromosome contacts. If you want to reconstruct the 3D structures of all chromosomes, you will need to run the code on each chromosome separately and provide it to the chr_name parameter (e.g. chr_name=chr1, chr_name=chr2, etc). The current version of the code does not provide a functionality to reconstruct the 3D structures of all chromosomes altogether.
